### ISSUE TITLE
add ete2 (python)

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/microgvl.ansible.filesystem#1]
hard to build with Qt

**Comment by tseemann** [comment]
this one is pip but a bit of a mess

**Comment by Slugger70** [comment]
We could use the conda version.

http://etetoolkit.org/download/

I could wrap it up in a module file. So the anaconda would only be added to the path when the module is loaded..

**Comment by Slugger70** [comment]
Get and install Miniconda and ete3
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O Miniconda-latest-Linux-x86_64.sh
bash Miniconda-latest-Linux-x86_64.sh -b -p ~/anaconda_ete/
export PATH=~/anaconda_ete/bin:$PATH;

# Install ETE

conda install -c etetoolkit ete3 ete3_external_apps

**Comment by Slugger70** [comment]
Now need a module file with the path export for anaconda and call it ete3.. Therefore, for a user to use ete3 they would first need to `module load ete3`

**Comment by Slugger70** [comment]
To install ete3 I used the following.. This will be added to the ansible script in the visualisers task

```
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O Miniconda-latest-Linux-x86_64.sh
bash Miniconda-latest-Linux-x86_64.sh -b -p /mnt/gvl/apps/anaconda_ete/
export PATH=/mnt/gvl/apps/anaconda_ete/bin:$PATH;

# Install ETE
conda install -c etetoolkit ete3 ete3_external_apps
```

**Comment by Slugger70** [comment]
Module file built
