### ISSUE TITLE
Add Snippy to toolshed

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#20]
Because snpEff is a nightmare to use in Galaxy unless your reference genome is in it.

Key input:
- GENBANK (for effects) otherwise FASTA
- R1 FASTQ
- R2 FASTQ
- cpus

Important Outputs:
- snps.vcf  ( + snps.tab / snps.csv / snps.html ?)
- snps.gff /  snps.bed (if jbrowse does not work with snps.vcf)

**Comment by Slugger70** [comment]
**Snippy** is now in testtoolshed. Works as well as snippy-core.. I have written a test workflow to go from read pairs and reference gbk to a newick tree.. via **snippy** and **snippy-core**
