### ISSUE TITLE
Add PHAC's SNVphyl pipeline

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#21]
Is it possible to put this in our Galaxy?

https://github.com/apetkau/snvphyl-galaxy

The SNVPhyl (SNV PHYLogenomics) pipeline is a pipeline for identifying Single Nucleotide Variants (SNV) within a collection of microbial genomes and constructing a phylogenetic tree. Detailed documentation can be found at http://snvphyl.readthedocs.org/. This repository contains the customized Galaxy tools for this pipeline as well as the source for the documentation.

**Comment by tseemann** [comment]
Also you said you can bundle it in it's own 'menu' so it doesn't pollute the name-space

**Comment by Slugger70** [comment]
This is done. If you install the irida platform, snvPhyl gets installed in it's own category on the Galaxy server on the same machine.

**Comment by Slugger70** [comment]
The tools get added to galaxy in the gvl as part of the irida installation. It might be best to leave it like this for now.
