### ISSUE TITLE
Roary for Galaxy

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/microgvl.ansible.filesystem#24]
Wrap AJ Page's **Roary** microbial pan genome analyser for Galaxy. It has a long list of dependencies, most of which aren't wrapped for Galaxy.

See:

**Comment by madisonkeene** [comment]
@Slugger70 I don't think I'm going to get to this (or finish it!) before I leave :( :( :(

**Comment by Slugger70** [comment]
Oh well..

**Comment by madisonkeene** [comment]
Waiting until conda wrapper- too complex to do any other way. Closing as invalid for now.
