### ISSUE TITLE
Do you need any Genbank/GFF conversion scripts?

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#25]
I have a bioperl script which can GBK -> GFF {1,2,3} which could be useful?

Or should we wrap `readseq` (java) ?

**Comment by Slugger70** [comment]
I've installed some GFF etc conversion utilities to Galaxy. They will convert between genbank, various GFFs, BEDs etc.. Located in convert format. on http://115.146.90.226/

TO DO: Add to mGVL fs tarball.

**Comment by Slugger70** [comment]
TO DO is done.

**Comment by tseemann** [comment]
The GBK to GFF doesn't work properly.  @annasyme

**Comment by madisonkeene** [comment]
@tseemann if the GBK to GFF is still an issue (its from 4 months ago so not sure) can you please open a new issue? :) thanks!
