### ISSUE TITLE
Enable VCF support on JBrowse for Snippy

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#26]
"Supports GFF3, BED, FASTA, Wiggle, BigWig, BAM, VCF (with tabix), REST, and more.  BAM, BigWig, and VCF data are displayed directly from chunks of the compressed binary files, no conversion needed."

The snippy result produces `snps.vcf.gz` and `snps.vcf.gz.tbi` which can be rendered.

This would be better than the `snps.gff`.

**Comment by Slugger70** [comment]
It's already enabled. I display it...

**Comment by tseemann** [comment]
Ok - last one you showed me was GFF with "A -> T" labels etc. Sorry!
