### ISSUE TITLE
Why does .gbk import as .txt ?

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#27]

**Comment by Slugger70** [comment]
There is no sniffer for genbank files.. It needs to be manually set. It's very very good practice to do this with EVERY file you load into galaxy (manually set it's file type) as Galaxy frequently gets it wrong. I STRESS this in every course/workshop I run.

**Comment by tseemann** [comment]
File format detection is not hard. You'll need to point me at the person in charge at GCC so I can talk to them.

**Comment by tseemann** [comment]
How do we add more sniffers?

**Comment by Slugger70** [comment]
I don't know. It's best practice to manually set the file type. The
sniffers get it wrong too many times. Escpecially when the files are
compressed.

**Comment by Slugger70** [comment]
Fixed. Needed a new line in datatypes_conf.xml
