### ISSUE TITLE
Add ABRicate to toolshed

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/microgvl.ansible.filesystem#31]

**Comment by tseemann** [comment]
I think this is now in Conda if that helps

**Comment by madisonkeene** [comment]
wrapper done - https://github.com/madiflannery/galaxy-wrappers

**Comment by Slugger70** [comment]
Currently in test tool shed. Have submitted pull request to tools-iuc repo so it can be included as an iuc tool in main toolshed.
