### ISSUE TITLE
install_linuxbrew.yml  - 'dict object' has no attribute 'INFOPATH' 

### ISSUE THREAD

**Issue by mthang** [gvlproject/microgvl.ansible.filesystem#35]
Hi, I received this error message when running the mGVL playbook " no attribute INFOPATH".

fatal: [203.101.230.121]: FAILED! => {"failed": true, "msg": "{u'INFOPATH': u'{{ gvl_app_path }}/linuxbrew                                                     /share/info:{{ ansible_env.INFOPATH }}', u'TEMP': u'{{ gvl_tmp_path}}', u'HOMEBREW_TEMP': u'{{ microgvl_homebrew_temp }}', u'HOMEBREW_CACHE': u'{{ microgvl_homebrew_cache }}', u'MANPATH': u'{{ gvl_app_path }}/linuxbrew/share/man:{{ ansible_env.MANPATH }}', u'TEMPDIR': u'{{ gvl_tmp_path }}', u'PATH': u'{{ gvl_app_path}}/linuxbrew/bin:{{ gvl_app_path }}/linuxbrew/sbin:{{ ansible_env.PATH }}'}: 'dict object' has no attribute 'INFOPATH'"}

**Comment by tseemann** [comment]
@Slugger70  I don't know what the error is, but `INFOPATH` needs to be set as per the Linuxbrew instructions at http://linuxbrew.sh/

**Comment by Slugger70** [comment]
The weird part is that it just stopped working for me too.. It looks as though the new version of ansible no longer has an INFOPATH var in it's env. I'll have to work on it.

**Comment by Slugger70** [comment]
Prior to installation of linuxbrew, INFOPATH is added to linuxbrewpath.sh in profile.d. Need to test the script without INFOPATH in the dictionary.

**Comment by mthang** [comment]
Hi, I have looked into the "profile.d", but the linuxbrewpath.sh file does not exist. isn't the installation of linuxbrew automatic through the playbook?

I still received the same error message when following the step in mGVL playbook "https://github.com/gvlproject/microgvl.ansible.filesystem"

**Comment by Slugger70** [comment]
It looks as though the INFOPATH is not set in ubuntu as part of the standard env. Therefore, this is the first entry in the INFOPATH. I've removed the :{{ ansible_env.INFOPATH }} from the ansible defaults/main.yml file. Fixed with commit 28d52cac2258cee7540016fe05e6614a3c9e85b9
