### ISSUE TITLE
Add Bioconductor "Differential Count models" to mGVL Galaxy

### ISSUE THREAD

**Issue by AnnaSyme** [gvlproject/microgvl.ansible.filesystem#41]
Could this be added please? 

(I thought it used to be there but I can't see it: under NGS:RNA Analysis: Differential Count models). I mainly want to use Voom/Limma. 

Thanks!

**Comment by Slugger70** [comment]
It is there. If you use the **NGS:RNA Analysis ->Differential Count models** tool.
Set **Run the same model with Voom/limma and compare findings** to  _run Voom_.
(it uses limma as well..) See the readme at the bottom of the tool for details.
