### ISSUE TITLE
Minor fix needed in file "install_other_brew_tools.yml"

### ISSUE THREAD

**Issue by mthang** [gvlproject/microgvl.ansible.filesystem#42]
Hi
There is a minor fix needed in this file "https://github.com/gvlproject/microgvl.ansible.filesystem/blob/master/tasks/install_other_brew_tools.yml"

line 35 has a syntax error. It should be "with_items" instead of "with-items"

**Comment by Slugger70** [comment]
done. Please submit pull requests.
