### ISSUE TITLE
No 'admin' group - confusion with 'adm' group?

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#46]
When unix users are added, and we want them to have sudo privileges, they are put in the `adm` group. But this only allows access to logs. The `/etc/sudoers` file has `admin` user. But there is no `admin` group. Confused!

**Comment by Slugger70** [comment]
This is a GVL issue. Can you move it to the GVL repo?

**Comment by tseemann** [comment]
How do I 'move' a github issue?

**Comment by madisonkeene** [comment]
You'll need to just open a new issue in the GVL repo, then mark this one as invalid and close it - https://github.com/gvlproject/gvl.ansible.playbook/ or https://overv.io/gvlproject/gvl.ansible.playbook/

**Comment by tseemann** [comment]
@madiflannery i thought there might be a 'nice' way to do it rather than cut & paste :) 

thank you.

**Comment by madisonkeene** [comment]
Not that I know of :( no worries!

**Comment by tseemann** [comment]
Can someone here please move this issue

**Comment by madisonkeene** [comment]
Moved here: https://github.com/gvlproject/gvl.ansible.playbook/issues/62
