### ISSUE TITLE
add circlator

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/microgvl.ansible.filesystem#5]

**Comment by tseemann** [comment]
pip install circlator

**Comment by Slugger70** [comment]
need to specifically install python3 numpy..

### Install Python 3 that will be managed by Homebrew

brew install python3

### Get access to the scientific Python formulas

brew tap Homebrew/python

### Install Numpy and Matplotlib

brew install numpy --with-python3
brew install matplotlib --with-python3

**Comment by tseemann** [comment]
Related issue: https://github.com/Homebrew/homebrew-science/issues/3707

**Comment by Slugger70** [comment]
Ansible needed to install things for python3.. including circlator

 # Install some python3 packages too!
- name: Install some python3 packages
  pip: name="{{ item }}" executable=pip3
  with_items:
    - numpy
    - circlator
    - matplotlib

**Comment by Slugger70** [comment]
Passes test
