### ISSUE TITLE
ABRPI: GS importer/exporter URL change

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/microgvl.ansible.filesystem#55]
The URL that the genomespace importer/exporter points to on ABRPI needs to be changed from genomespace-dev.genome.edu.au to genomespace.genome.edu.au

**Comment by Slugger70** [comment]
I have changed the URLs for the genomespace server in the files according to the top two tasks in https://github.com/gvlproject/gvl.ansible.filesystem/blob/master/tasks/configure_galaxy.yml

I cannot restart the server at the moment as it's being used for a course

**Comment by madisonkeene** [comment]
Not good enough @Slugger70 :P

**Comment by madisonkeene** [comment]
This is probably OK. Closing.
