### ISSUE TITLE
Put refseq in swift

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/microgvl.ansible.filesystem#6]
This shows the URL to put in swift: https://github.com/DerrickWood/kraken/commit/5cc8d1a5cb34c02b1f68c615ea2a73f364703d76
Then untar it somewhere for the uGVL to use.

**Comment by madisonkeene** [comment]
ftp.ncbi.nlm.nih.gov/genomes/archive/old_refseq/Bacteria/all.fna.tar.gz

**Comment by Slugger70** [comment]
Used the URL as suggested by Torsten and put it all into galaxyIndices and will make it an option in the launcher to use it or not.
